version: '3.9'

# services:
#   db:
#     image: postgis/postgis
#     restart: no
#     shm_size: 128mb
#     environment:
#       POSTGRES_PASSWORD: sql@123
#       POSTGRES_USER: postgres
#       POSTGRES_DB: aleeviadb
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# volumes:
#   postgres_data:
